### ISSUE TITLE
Incorporate OCR as part of derivative creation process

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/assembly#145]
Currently, the only content that can be OCRed must go through Goobi. Ideally, OCR would take place during the derivative creation process in assembly, so that content accessioned through preassembly, the self-deposit app, and Goobi could all take advantage of OCR technology. This would also allow us to explore other OCR software, and have more control over the OCR software with regards to monitoring.

**Comment by jcoyne** [comment]
See https://github.com/sul-dlss/common-accessioning/issues/229
