### ISSUE TITLE
Since late January, all new Hydrus APOs fail Assembly

### ISSUE THREAD

**Issue by blalbrit** [sul-dlss/assembly#57]
It looks like this release: https://github.com/sul-dlss/assembly/releases/tag/v3.1.3 prompted an issue with Hydrus APO objects, causing them to fail the checksum-compute step and subsequent steps with an error of "undefined method 'id' for {druid}: String".

Because the APOs don't pass Assembly, they also fail Accessioning, causing downstream issues for the stakeholders and the repository.

See list of impacted objects at the moment: https://argo.stanford.edu/catalog?f%5Bnonhydrus_apo_title_ssim%5D%5B%5D=Hydrus+Ur-APO&f%5Bwf_wps_ssim%5D%5B%5D=assemblyWF%3Achecksum-compute%3Aerror

**Comment by peetucket** [comment]
minor logging issue; proposed fix in #59
